### ISSUE TITLE
StepsWasNotUsed raised if test was dynamicly skipped

### ISSUE THREAD

**Issue by griddic** [oztqa/pytest-allure-dsl#10]
Consider test:
```python
def test_test(allure_dsl):
    """
    steps:
        1: first
        2: second
    """"
    with allure_dsl.step(1):
        if condition:
            pytest.skip(reason)
    with allure_dsl.step(2):
        do_smth()
```

If test dynamicly skipped StepsWasNotUsed(2) error will be raised. 
In this case test will be in status "ERROR" instead of "SKIPPED".

**Comment by griddic** [comment]
It looks like we should raise StepsWasNotUsed ONLY if test was passed.

**Comment by trifonovmixail** [comment]
@griddic https://github.com/oztqa/pytest-allure-dsl/pull/11
